#!/usr/bin/env python3
"""Red answer sketches for the exam graph questions, placed from a fresh calibration of
the final crops (axes and grid pitch read from pixels, never by eye).  Writes
fig/ppfull/<id>_ans.tex.  Re-run after any re-crop.

Graph readings (tutor's working, grid squares unless stated):
  a21_2a  f has turning points at x = -6, 0, 6 (min -5, max 16) -> f' = k x (x^2 - 36), k = 0.072 for display
  a21_3c  f'(x) = -0.5 (x - 2)(x - 10) (vertex (6, 8), f'(0) = -10) -> a possible f = 0.5(-x^3/6 + 3x^2 - 10x) - 4
  a22_2a  x unit = 1, y unit = 1 (labels): f'(x) = -1.5 (x + 3)(x + 1)(x - 3.5) -> a possible
          f = -0.375x^4 - 0.25x^3 + 8.25x^2 + 15.75x - 10
  a22_3b1 f = -x, g = x, h = x^2 (1 unit = 2 squares) -> f' = -1, g' = 1, h' = 2x
  a22_3b2 p = |x| -> p' = -1 (x < 0), 1 (x > 0), not defined at 0
"""
import os, sys
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from calib import calibrate

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'fig', 'ppfull')
import cv2


def avg_pitch(lines):
    return (lines[-1] - lines[0]) / (len(lines) - 1)


def scope(c, ux, uy, body, clip=True):
    bx0, by0, bx1, by1 = c['box']
    s = '\\begin{scope}\n'
    if clip:
        s += '  \\clip (%d,%d) rectangle (%d,%d);\n' % (bx0, by0, bx1, by1)
    s += '  \\begin{scope}[shift={(%.1f,%.1f)}, x={(%.3f,0)}, y={(0,%.3f)}]\n' % (c['axis_x'], c['axis_y'], ux, -uy)
    s += body
    s += '  \\end{scope}\n\\end{scope}\n'
    return s


def plot(expr, a, b):
    return ('    \\draw[ansred, line width=1.4pt, domain=%s:%s, samples=150, smooth, variable=\\x] plot (\\x,{%s});\n'
            % (a, b, expr))


def label(x, y, text, anchor='west'):
    return '    \\node[anchor=%s, text=ansred, font=\\small, align=left] at (%s,%s) {%s};\n' % (anchor, x, y, text)


def h(cid):
    return cv2.imread(os.path.join(OUT, cid + '.png'), 0).shape


def write(cid, tex):
    with open(os.path.join(OUT, cid + '_ans.tex'), 'w') as f:
        f.write('% generated by tools/graph_overlays.py -- do not edit\n' + tex)


def main():
    rep = []
    # ---- a21_2a: lower grid, units = grid squares
    H, W = h('a21_2a')
    c = calibrate('a21_2a', H // 2 + 60, H)
    ux, uy = avg_pitch(c['vlines']), avg_pitch(c['hlines'])
    body = plot('0.072*\\x*(\\x*\\x-36)', -8.7, 8.7)
    body += label(0.4, -21, 'zeros at the $x$-values of the\\\\ three \\tturns of $f$')
    write('a21_2a', scope(c, ux, uy, body))
    rep.append(('a21_2a', c))
    # ---- a21_3c: lower grid, squares
    H, W = h('a21_3c')
    c = calibrate('a21_3c', H // 2 + 60, H)
    ux, uy = avg_pitch(c['vlines']), avg_pitch(c['hlines'])
    body = plot('0.5*(-\\x*\\x*\\x/6+3*\\x*\\x-10*\\x)-4', -5, 15)
    body += label(2.3, -10.5, 'minimum above $x=2$,\\\\ maximum above the\\\\ right zero of $f\'$')
    write('a21_3c', scope(c, ux, uy, body))
    rep.append(('a21_3c', c))
    # ---- a22_2a: lower grid, labelled units (x: 5 squares, y: 20 per 4 squares)
    H, W = h('a22_2a')
    c = calibrate('a22_2a', H // 2 + 60, H, 400, W)
    ux, uy = avg_pitch(c['vlines']) * 5, avg_pitch(c['hlines']) / 5
    body = plot('-0.375*\\x*\\x*\\x*\\x-0.25*\\x*\\x*\\x+8.25*\\x*\\x+15.75*\\x-10', -4.9, 5.3)
    body += label(-4.8, 88, 'max at $x=-3$, min at $x=-1$,\\\\ max at $x=3.5$ (any height)')
    write('a22_2a', scope(c, ux, uy, body))
    rep.append(('a22_2a', c))
    # ---- a22_3b1: three lower grids, 1 unit = 2 squares
    H, W = h('a22_3b1')
    tex = ''
    for (x0, x1), expr in zip([(125, 788), (795, 1457), (1464, 2126)], ['-1', '1', '2*\\x']):
        c = calibrate('a22_3b1', int(H * 0.58), H, x0, x1)
        u = avg_pitch(c['vlines']) * 2
        tex += scope(c, u, u, plot(expr, -5, 5))
        rep.append(('a22_3b1', c))
    write('a22_3b1', tex)
    # ---- a22_3b2: lower grid (p'), step function with open circles, then text on the rules
    H, W = h('a22_3b2')
    c = calibrate('a22_3b2', int(H * 0.33), int(H * 0.62), 300, 1950)
    u = avg_pitch(c['vlines']) * 2
    body = ('    \\draw[ansred, line width=1.4pt] (-7,-1) -- (-0.12,-1) (0.12,1) -- (7,1);\n'
            '    \\draw[ansred, line width=1pt, fill=white] (0,-1) circle (0.12) (0,1) circle (0.12);\n')
    tex = scope(c, u, u, body)
    tex += ('\\ppline{1}{No. $p$ has a sharp corner at $x=0$.}\n'
            '\\ppline{2}{Left of $0$ the gradient is $-1$; right of $0$ it is $1$.}\n'
            '\\ppline{3}{The gradient jumps at $x=0$, so it is not defined there: it is not $0$.}\n'
            '\\ppline{4}{(The open circles on $p\'(x)$ show there is no value at $x=0$.)}\n')
    write('a22_3b2', tex)
    rep.append(('a22_3b2', c))
    for cid, c in rep:
        print('%-8s axis (%.1f, %.1f) pitch %.2f x %.2f  box %s' % (cid, c['axis_x'] or -1, c['axis_y'] or -1,
              avg_pitch(c['vlines']), avg_pitch(c['hlines']), c['box']))


if __name__ == '__main__':
    main()
